import type {
  CourseForm as CourseFormState,
  SplitForm as SplitFormState,
  DayHoursEntry,
} from "./types";
import { makeDefaultDayHours } from "./types";
import { makeDefaultSplit } from "./defaults";
import { browserTimezone } from "./components/TimezoneSelect";
import type { ExampleEntry } from "./components/ExampleModal";

function exampleSplit(overrides: Partial<SplitFormState>): SplitFormState {
  return { ...makeDefaultSplit(), ...overrides };
}

function sevenDays(
  entry: DayHoursEntry,
): [
  DayHoursEntry,
  DayHoursEntry,
  DayHoursEntry,
  DayHoursEntry,
  DayHoursEntry,
  DayHoursEntry,
  DayHoursEntry,
] {
  return [entry, entry, entry, entry, entry, entry, entry];
}

function toLocalDatetime(iso: string): string {
  const d = new Date(iso);
  const offset = d.getTimezoneOffset();
  return new Date(d.getTime() - offset * 60000).toISOString().slice(0, 16);
}

const SIMPLE_EXAMPLE_FORM: CourseFormState = {
  unitSystem: "imperial",
  timezone: browserTimezone,
  mode: "distance",
  init_moving_speed: "18",
  min_moving_speed: "16",
  down_time_ratio: "0.05",
  split_decay: "0.1",
  start_time: toLocalDatetime("2026-04-11T11:00:00.000Z"),
  segmentCount: "1",
  segments: [
    {
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "2",
      splits: [
        exampleSplit({
          distance: "50",
          sub_split_mode: "even",
          sub_split_count: "3",
        }),
        exampleSplit({
          distance: "50",
          sub_split_mode: "fixed",
          sub_split_distance: "20",
          last_sub_split_threshold: "20",
          rest_stop: {
            enabled: true,
            name: "Specialized Chicago",
            address: "925 W Lake St Ste 1100/1110, Chicago, IL 60607",
            alt: "https://www.specialized.com/us/en/store-finder/specialized-chicago-fulton-market/6407248",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: [
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "17:00" },
              { mode: "hours", opens: "11:30", closes: "16:00" },
            ],
          },
        }),
      ],
    },
  ],
};

const COMPLEX_EXAMPLE_FORM: CourseFormState = {
  unitSystem: "imperial",
  timezone: browserTimezone,
  mode: "target_distance",
  init_moving_speed: "17",
  min_moving_speed: "16",
  down_time_ratio: "0.1",
  split_decay: "0.1",
  start_time: toLocalDatetime("2026-04-11T11:00:00.000Z"),
  segmentCount: "2",
  segments: [
    {
      sleep_time: "360",
      include_end_down_time: true,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "2",
      splits: [
        exampleSplit({
          distance: "50",
          sub_split_mode: "even",
          sub_split_count: "3",
          rest_stop: {
            enabled: true,
            name: "Taqueria El Sol",
            address: "3100 14th St NW, Washington, DC 20010",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "17:00", closes: "23:00" },
            perDay: [
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
            ],
          },
        }),
        exampleSplit({
          distance: "100",
          sub_split_mode: "even",
          sub_split_count: "1",
          down_time: "750",
          differentTimezone: true,
          timezone: "America/New_York",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "1539 Pennsylvania Ave. SE, Washington, DC",
            alt: "https://www.mcdonalds.com/us/en-us/location/DC/WASHINGTON/1539-PENNSYLVANIA-SE/7394.html",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: [
              { mode: "hours", opens: "05:30", closes: "02:00" },
              { mode: "hours", opens: "05:30", closes: "02:00" },
              { mode: "hours", opens: "05:30", closes: "02:00" },
              { mode: "hours", opens: "05:30", closes: "03:00" },
              { mode: "hours", opens: "05:30", closes: "03:00" },
              { mode: "hours", opens: "05:30", closes: "03:00" },
              { mode: "hours", opens: "05:30", closes: "02:00" },
            ],
          },
        }),
      ],
    },
    {
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "2",
      splits: [
        exampleSplit({
          distance: "150",
          sub_split_mode: "fixed",
          sub_split_distance: "20",
          last_sub_split_threshold: "10",
        }),
        exampleSplit({
          distance: "198",
          sub_split_mode: "fixed",
          sub_split_distance: "20",
          last_sub_split_threshold: "10",
          adjustment_time: "",
          rest_stop: {
            enabled: true,
            name: "Home",
            address: "1600 Pennsylvania Ave NW, Washington, DC 20500",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
            ],
          },
        }),
      ],
    },
  ],
};

// Mishigami — 1121.2 mi unsupported ultra-cycling loop around Lake Michigan
const MISHIGAMI_EXAMPLE_FORM: CourseFormState = {
  name: "Mishigami 2025",
  unitSystem: "imperial",
  timezone: "America/Chicago",
  mode: "target_distance",
  init_moving_speed: "16.5",
  min_moving_speed: "15",
  down_time_ratio: "0.12",
  split_decay: "0.25",
  start_time: "2025-07-12T06:00",
  segmentCount: "2",
  segments: [
    {
      // Chicago → St Ignace
      name: "Chicago to St Ignace",
      sleep_time: "240",
      include_end_down_time: true,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "5",
      splits: [
        {
          name: "Chicago to Milwaukee",
          distance: "114.3",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "7170 N Teutonia Ave, Milwaukee, WI 53209",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "21:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: false,
          timezone: "America/Chicago",
        },
        {
          name: "Milwaukee to Green Bay",
          distance: "246.5",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Shell Gas Station",
            address: "1010 S Broadway, De Pere, WI 54115",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: false,
          timezone: "America/Chicago",
        },
        {
          name: "Green Bay to Bark River",
          distance: "394.3",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "bp",
            address: "W365 US-2 #41, Harris, MI 49845",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "01:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Bark River to Blaney Park",
          distance: "480.7",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "bp",
            address: "1223 US-2, Gulliver, MI 49840",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "07:00", closes: "21:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Blaney Park to St Ignace",
          distance: "571.5",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Best Western Harbour Pointe Lakefront",
            address: "797 N State St, St Ignace, MI 49781",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "15:00", closes: "11:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
      ],
    },
    {
      // St Ignace → Chicago
      name: "St Ignace to Chicago",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "5",
      splits: [
        {
          name: "St Ignace to Elk Rapids",
          distance: "696.8",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Mobil",
            address: "100 First Street, Elk Rapids, MI",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "05:00", closes: "23:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Elk Rapids to Manistee",
          distance: "805.3",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Wesco",
            address: "75 Cypress St, Manistee, MI 49660",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Manistee to Beechwood",
          distance: "936.2",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "213 N River Ave, Holland, MI 49424",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "30",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Beechwood to New Buffalo",
          distance: "1036.2",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Barney's",
            address: "10 N Thompson St, New Buffalo, MI 49117",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "07:00", closes: "21:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "New Buffalo to Chicago",
          distance: "1115.2",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: false,
            name: "",
            address: "",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: false,
          timezone: "America/Chicago",
        },
      ],
    },
  ],
};

const TRANS_AM_CLASSIC_2026: CourseFormState = {
  name: "TRANS AM CLASSIC 2026",
  unitSystem: "imperial",
  mode: "distance",
  timezone: "America/Los_Angeles",
  init_moving_speed: "16",
  min_moving_speed: "10",
  down_time_ratio: "0.1",
  split_decay: "0.1",
  start_time: toLocalDatetime("2026-04-09T21:50:00.000Z"),
  segmentCount: "18",
  segments: [
    {
      name: "Astoria → Sisters",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60.7",
          name: "Astoria → Garibaldi",
          rest_stop: {
            enabled: true,
            name: "Shell",
            address: "45.559099, -123.915158",
            alt: "",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: sevenDays({
              mode: "hours",
              opens: "06:00",
              closes: "21:00",
            }),
          },
        }),
        exampleSplit({
          distance: "112.5",
          name: "Garibaldi → Monmouth",
          notes: "We need to get Cheese Sticks, Sarah Rice advises!",
          rest_stop: {
            enabled: true,
            name: "Domino's",
            address: "44.848694, -123.232835",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "closed", opens: "06:00", closes: "22:00" },
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "56",
          name: "Monmouth → Coburg",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "91027 Coburg Industrial Way, Coburg, OR",
            alt: "",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: sevenDays({
              mode: "hours",
              opens: "06:00",
              closes: "22:00",
            }),
          },
        }),
        exampleSplit({
          distance: "97",
          name: "Coburg → Sisters",
          differentTimezone: true,
          timezone: "America/Boise",
          notes: "There is a dollar general in the same plaza.",
          rest_stop: {
            enabled: true,
            name: "Bi-Mart",
            address: "445 West Highway 20, Sisters, OR",
            alt: "",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: [
              { mode: "hours", opens: "06:00", closes: "19:00" },
              { mode: "hours", opens: "06:00", closes: "19:00" },
              { mode: "hours", opens: "06:00", closes: "19:00" },
              { mode: "hours", opens: "06:00", closes: "19:00" },
              { mode: "hours", opens: "06:00", closes: "19:00" },
              { mode: "hours", opens: "06:00", closes: "18:00" },
              makeDefaultDayHours(),
            ],
          },
        }),
      ],
    },
    {
      name: "Sisters → Cambridge",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "38",
          name: "Sisters → Prineville",
          notes: "Long stretch ahead, low resources.",
          rest_stop: {
            enabled: true,
            name: "Chevron",
            address: "44.302737, -120.850253",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "118",
          name: "Prineville → John Day",
          rest_stop: {
            enabled: true,
            name: "Subway",
            address: "44.415564, -118.952484",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "07:00", closes: "20:00" },
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "78",
          name: "John Day → Baker City",
          rest_stop: {
            enabled: true,
            name: "Maverik",
            address: "44.781929, -117.822698",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "109",
          name: "Baker City → Cambridge",
          differentTimezone: true,
          timezone: "America/Boise",
          rest_stop: {
            enabled: true,
            name: "Blake's",
            address: "44.571691, -116.677110",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "22:00" },
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
      ],
    },
    {
      name: "Cambridge → Ravalli County",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "47",
          name: "Cambridge → New Meadows",
          differentTimezone: true,
          timezone: "America/Boise",
          rest_stop: {
            enabled: true,
            name: "Chevron",
            address: "44.971442, -116.281697",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "05:00", closes: "20:00" },
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "71.5",
          name: "New Meadows → Idaho County",
          differentTimezone: true,
          timezone: "America/Boise",
          rest_stop: {
            enabled: true,
            name: "Subway",
            address: "179 Greenacres Lane, Grangeville, ID",
            alt: "",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: sevenDays({
              mode: "hours",
              opens: "06:00",
              closes: "20:00",
            }),
          },
        }),
        exampleSplit({
          distance: "120",
          name: "Idaho County → Idaho County",
        }),
        exampleSplit({
          distance: "60",
          name: "Idaho County → Ravalli County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
      ],
    },
    {
      name: "Ravalli County → Madison County",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Ravalli County → Ravalli County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Ravalli County → Beaverhead County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Beaverhead County → Madison County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Madison County → Madison County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
      ],
    },
    {
      name: "Madison County → Fremont County",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Madison County → Gallatin County",
        }),
        exampleSplit({
          distance: "60",
          name: "Gallatin County → Teton County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Teton County → Teton County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Teton County → Fremont County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
      ],
    },
    {
      name: "Fremont County → Carbon County",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Fremont County → Fremont County",
        }),
        exampleSplit({
          distance: "60",
          name: "Fremont County → Fremont County",
        }),
        exampleSplit({
          distance: "60",
          name: "Fremont County → Natrona County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Natrona County → Carbon County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
      ],
    },
    {
      name: "Carbon County → Summit County",
      sleep_time: "480",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Carbon County → Carbon County",
        }),
        exampleSplit({
          distance: "60",
          name: "Carbon County → Jackson County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Jackson County → Grand County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Grand County → Summit County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
      ],
    },
    {
      name: "Summit County → Crowley County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Summit County → Park County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Park County → Fremont County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Fremont County → Pueblo",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
        exampleSplit({
          distance: "60",
          name: "Pueblo → Crowley County",
          differentTimezone: true,
          timezone: "America/Denver",
        }),
      ],
    },
    {
      name: "Crowley County → Rush County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Crowley County → Kiowa County",
        }),
        exampleSplit({
          distance: "60",
          name: "Kiowa County → Greeley County",
        }),
        exampleSplit({
          distance: "60",
          name: "Greeley County → Dighton",
        }),
        exampleSplit({ distance: "60", name: "Dighton → Rush County" }),
      ],
    },
    {
      name: "Rush County → Woodson County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Rush County → Stafford County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Stafford County → Harvey County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Harvey County → Butler County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Butler County → Woodson County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
      ],
    },
    {
      name: "Woodson County → Wright County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Woodson County → Neosho County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Neosho County → Barton County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Barton County → Greene County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Greene County → Wright County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
      ],
    },
    {
      name: "Wright County → Jackson County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Wright County → Shannon County",
        }),
        exampleSplit({
          distance: "60",
          name: "Shannon County → Reynolds County",
        }),
        exampleSplit({
          distance: "60",
          name: "Reynolds County → Ste. Genevieve County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
        exampleSplit({
          distance: "60",
          name: "Ste. Genevieve County → Jackson County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
      ],
    },
    {
      name: "Jackson County → Breckinridge County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Jackson County → Johnson County",
        }),
        exampleSplit({
          distance: "60",
          name: "Johnson County → Crittenden County",
        }),
        exampleSplit({
          distance: "60",
          name: "Crittenden County → Daviess County",
        }),
        exampleSplit({
          distance: "60",
          name: "Daviess County → Breckinridge County",
          differentTimezone: true,
          timezone: "America/Chicago",
        }),
      ],
    },
    {
      name: "Breckinridge County → Breathitt County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Breckinridge County → Nelson County",
        }),
        exampleSplit({
          distance: "60",
          name: "Nelson County → Washington County",
        }),
        exampleSplit({
          distance: "60",
          name: "Washington County → Berea",
        }),
        exampleSplit({
          distance: "60",
          name: "Berea → Breathitt County",
          differentTimezone: true,
          timezone: "America/New_York",
        }),
      ],
    },
    {
      name: "Breathitt County → Wythe County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Breathitt County → Knott County",
          differentTimezone: true,
          timezone: "America/New_York",
        }),
        exampleSplit({
          distance: "60",
          name: "Knott County → Dickenson County",
          differentTimezone: true,
          timezone: "America/New_York",
        }),
        exampleSplit({
          distance: "60",
          name: "Dickenson County → Washington County",
          differentTimezone: true,
          timezone: "America/New_York",
        }),
        exampleSplit({
          distance: "60",
          name: "Washington County → Wythe County",
          differentTimezone: true,
          timezone: "America/New_York",
        }),
      ],
    },
    {
      name: "Wythe County → Albemarle County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Wythe County → Montgomery County",
        }),
        exampleSplit({
          distance: "60",
          name: "Montgomery County → Botetourt County",
        }),
        exampleSplit({
          distance: "60",
          name: "Botetourt County → Rockbridge County",
        }),
        exampleSplit({
          distance: "60",
          name: "Rockbridge County → Albemarle County",
          differentTimezone: true,
          timezone: "America/New_York",
        }),
      ],
    },
    {
      name: "Albemarle County → York County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "4",
      splits: [
        exampleSplit({
          distance: "60",
          name: "Albemarle County → Louisa County",
        }),
        exampleSplit({
          distance: "60",
          name: "Louisa County → Hanover County",
        }),
        exampleSplit({
          distance: "60",
          name: "Hanover County → Williamsburg",
        }),
        exampleSplit({
          distance: "60",
          name: "Williamsburg → York County",
        }),
      ],
    },
    {
      name: "York County → York County",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "3",
      splits: [
        exampleSplit({
          distance: "59",
          name: "York County → York County",
          rest_stop: {
            enabled: true,
            name: "Exxon",
            address: "38.010604, -77.908607",
            alt: "",
            sameHoursEveryDay: true,
            allDays: makeDefaultDayHours(),
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "60",
          name: "York County → York County",
          differentTimezone: true,
          timezone: "America/New_York",
          rest_stop: {
            enabled: true,
            name: "Panera Bread",
            address: "7320 Bell Creek Road, Mechanicsville, VA",
            alt: "",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
        exampleSplit({
          distance: "83.1",
          name: "York County → York County",
          differentTimezone: true,
          timezone: "America/New_York",
          rest_stop: {
            enabled: true,
            name: "Riverwalk Restaurant",
            address: "323 Water Street, Yorktown, VA",
            alt: "",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: sevenDays(makeDefaultDayHours()),
          },
        }),
      ],
    },
  ],
};

export const EXAMPLES: ExampleEntry[] = [
  {
    name: "Simple — 100 mi Day Ride",
    description:
      "Single segment, 2 splits (even + fixed sub-splits), one rest stop with open hours.",
    form: SIMPLE_EXAMPLE_FORM,
    url_name: "simple",
  },
  {
    name: "Complex — 198 mi Multi-Day",
    description:
      "2 segments with sleep, 4 splits, timezone overrides, multiple rest stops with per-day hours, even + fixed sub-split modes.",
    form: COMPLEX_EXAMPLE_FORM,
    url_name: "complex",
  },
  {
    name: "Mishigami 2025 — 1115.2 mi Around Lake Michigan",
    description:
      "2 segments (Chicago ↔ St Ignace), 10 splits with rest stops, imperial, fixed 50 mi sub-splits, 4h sleep at turnaround.",
    form: MISHIGAMI_EXAMPLE_FORM,
    gpxUrl: "./examples/Mishigami-2025_Official.gpx",
    url_name: "mishigami-2025",
  },
  {
    name: "Trans Am Classic Route — ~4200 mi Coast to Coast",
    description:
      "18 segments, 4 splits each, 8h sleep on days 1-7, Astoria OR to Yorktown VA. Pacific → Mountain → Central → Eastern timezone crossings.",
    form: TRANS_AM_CLASSIC_2026,
    gpxUrl: "./examples/Trans_Am_Classic_Route_2026.gpx",
    url_name: "trans-am-2026",
  },
];
