import type {
  CourseForm as CourseFormState,
  SplitForm as SplitFormState,
} from "./types";
import { makeDefaultDayHours } from "./types";
import { makeDefaultSplit } from "./defaults";
import { browserTimezone } from "./components/TimezoneSelect";
import type { ExampleEntry } from "./components/ExampleModal";

function exampleSplit(overrides: Partial<SplitFormState>): SplitFormState {
  return { ...makeDefaultSplit(), ...overrides };
}

function toLocalDatetime(iso: string): string {
  const d = new Date(iso);
  const offset = d.getTimezoneOffset();
  return new Date(d.getTime() - offset * 60000).toISOString().slice(0, 16);
}

const SIMPLE_EXAMPLE_FORM: CourseFormState = {
  unitSystem: "imperial",
  timezone: browserTimezone,
  mode: "distance",
  init_moving_speed: "18",
  min_moving_speed: "16",
  down_time_ratio: "0.05",
  split_decay: "0.1",
  start_time: toLocalDatetime("2026-04-11T11:00:00.000Z"),
  segmentCount: "1",
  segments: [
    {
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "2",
      splits: [
        exampleSplit({
          distance: "50",
          sub_split_mode: "even",
          sub_split_count: "3",
        }),
        exampleSplit({
          distance: "50",
          sub_split_mode: "fixed",
          sub_split_distance: "20",
          last_sub_split_threshold: "20",
          rest_stop: {
            enabled: true,
            name: "Specialized Chicago",
            address: "925 W Lake St Ste 1100/1110, Chicago, IL 60607",
            alt: "https://www.specialized.com/us/en/store-finder/specialized-chicago-fulton-market/6407248",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: [
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "18:00" },
              { mode: "hours", opens: "11:00", closes: "17:00" },
              { mode: "hours", opens: "11:30", closes: "16:00" },
            ],
          },
        }),
      ],
    },
  ],
};

const COMPLEX_EXAMPLE_FORM: CourseFormState = {
  unitSystem: "imperial",
  timezone: browserTimezone,
  mode: "target_distance",
  init_moving_speed: "17",
  min_moving_speed: "16",
  down_time_ratio: "0.1",
  split_decay: "0.1",
  start_time: toLocalDatetime("2026-04-11T11:00:00.000Z"),
  segmentCount: "2",
  segments: [
    {
      sleep_time: "360",
      include_end_down_time: true,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "2",
      splits: [
        exampleSplit({
          distance: "50",
          sub_split_mode: "even",
          sub_split_count: "3",
          rest_stop: {
            enabled: true,
            name: "Taqueria El Sol",
            address: "3100 14th St NW, Washington, DC 20010",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "17:00", closes: "23:00" },
            perDay: [
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
            ],
          },
        }),
        exampleSplit({
          distance: "100",
          sub_split_mode: "even",
          sub_split_count: "1",
          down_time: "750",
          differentTimezone: true,
          timezone: "America/New_York",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "1539 Pennsylvania Ave. SE, Washington, DC",
            alt: "https://www.mcdonalds.com/us/en-us/location/DC/WASHINGTON/1539-PENNSYLVANIA-SE/7394.html",
            sameHoursEveryDay: false,
            allDays: makeDefaultDayHours(),
            perDay: [
              { mode: "hours", opens: "05:30", closes: "02:00" },
              { mode: "hours", opens: "05:30", closes: "02:00" },
              { mode: "hours", opens: "05:30", closes: "02:00" },
              { mode: "hours", opens: "05:30", closes: "03:00" },
              { mode: "hours", opens: "05:30", closes: "03:00" },
              { mode: "hours", opens: "05:30", closes: "03:00" },
              { mode: "hours", opens: "05:30", closes: "02:00" },
            ],
          },
        }),
      ],
    },
    {
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "2",
      splits: [
        exampleSplit({
          distance: "150",
          sub_split_mode: "fixed",
          sub_split_distance: "20",
          last_sub_split_threshold: "10",
        }),
        exampleSplit({
          distance: "198",
          sub_split_mode: "fixed",
          sub_split_distance: "20",
          last_sub_split_threshold: "10",
          adjustment_time: "",
          rest_stop: {
            enabled: true,
            name: "Home",
            address: "1600 Pennsylvania Ave NW, Washington, DC 20500",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
              makeDefaultDayHours(),
            ],
          },
        }),
      ],
    },
  ],
};

// Mishigami — 1121.2 mi unsupported ultra-cycling loop around Lake Michigan
const MISHIGAMI_EXAMPLE_FORM: CourseFormState = {
  name: "Mishigami 2025",
  unitSystem: "imperial",
  timezone: "America/Chicago",
  mode: "target_distance",
  init_moving_speed: "16.5",
  min_moving_speed: "15",
  down_time_ratio: "0.12",
  split_decay: "0.25",
  start_time: "2025-07-12T06:00",
  segmentCount: "2",
  segments: [
    {
      // Chicago → St Ignace
      name: "Chicago to St Ignace",
      sleep_time: "240",
      include_end_down_time: true,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "5",
      splits: [
        {
          name: "Chicago to Milwaukee",
          distance: "114.3",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "7170 N Teutonia Ave, Milwaukee, WI 53209",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "21:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: false,
          timezone: "America/Chicago",
        },
        {
          name: "Milwaukee to Green Bay",
          distance: "246.5",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Shell Gas Station",
            address: "1010 S Broadway, De Pere, WI 54115",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: false,
          timezone: "America/Chicago",
        },
        {
          name: "Green Bay to Bark River",
          distance: "394.3",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "bp",
            address: "W365 US-2 #41, Harris, MI 49845",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "01:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Bark River to Blaney Park",
          distance: "480.7",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "bp",
            address: "1223 US-2, Gulliver, MI 49840",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "07:00", closes: "21:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Blaney Park to St Ignace",
          distance: "571.5",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Best Western Harbour Pointe Lakefront",
            address: "797 N State St, St Ignace, MI 49781",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "15:00", closes: "11:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
      ],
    },
    {
      // St Ignace → Chicago
      name: "St Ignace to Chicago",
      sleep_time: "0",
      include_end_down_time: false,
      down_time_ratio: "",
      split_decay: "",
      moving_speed: "",
      min_moving_speed: "",
      splitCount: "5",
      splits: [
        {
          name: "St Ignace to Elk Rapids",
          distance: "696.8",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Mobil",
            address: "100 First Street, Elk Rapids, MI",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "05:00", closes: "23:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Elk Rapids to Manistee",
          distance: "805.3",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Wesco",
            address: "75 Cypress St, Manistee, MI 49660",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Manistee to Beechwood",
          distance: "936.2",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "McDonald's",
            address: "213 N River Ave, Holland, MI 49424",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "24h", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "30",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "Beechwood to New Buffalo",
          distance: "1036.2",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: true,
            name: "Barney's",
            address: "10 N Thompson St, New Buffalo, MI 49117",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "07:00", closes: "21:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: true,
          timezone: "America/Detroit",
        },
        {
          name: "New Buffalo to Chicago",
          distance: "1115.2",
          sub_split_mode: "fixed",
          sub_split_count: "1",
          sub_split_distance: "50",
          last_sub_split_threshold: "15",
          sub_split_distances: "",
          rest_stop: {
            enabled: false,
            name: "",
            address: "",
            alt: "",
            sameHoursEveryDay: true,
            allDays: { mode: "hours", opens: "06:00", closes: "22:00" },
            perDay: [
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
              { mode: "hours", opens: "06:00", closes: "22:00" },
            ],
          },
          down_time: "",
          moving_speed: "",
          adjustment_time: "",
          differentTimezone: false,
          timezone: "America/Chicago",
        },
      ],
    },
  ],
};

export const EXAMPLES: ExampleEntry[] = [
  {
    name: "Simple — 100 mi Day Ride",
    description:
      "Single segment, 2 splits (even + fixed sub-splits), one rest stop with open hours.",
    form: SIMPLE_EXAMPLE_FORM,
  },
  {
    name: "Complex — 198 mi Multi-Day",
    description:
      "2 segments with sleep, 4 splits, timezone overrides, multiple rest stops with per-day hours, even + fixed sub-split modes.",
    form: COMPLEX_EXAMPLE_FORM,
  },
  {
    name: "Mishigami 2025 — 1115.2 mi Around Lake Michigan",
    description:
      "2 segments (Chicago ↔ St Ignace), 10 splits with rest stops, imperial, fixed 50 mi sub-splits, 4h sleep at turnaround.",
    form: MISHIGAMI_EXAMPLE_FORM,
    gpxUrl: "./examples/Mishigami-2025_Official.gpx",
  },
];
